repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.17.0
    hooks:
      - id: check-github-workflows
      - id: check-dependabot
      # Schema is not compatible with a composite action
      # - id: check-github-actions
